server:
    port: 8100
    error:
        include-message: always
        include-binding-errors: always

logging:
    level:
        root: INFO

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/maivcdb
        username: postgres
        password: f
        driver-class-name: org.postgresql.Driver
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: create
